# Generated by Django 4.1.3 on 2022-11-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_transaction_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='expense_name',
            new_name='transaction_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Postive', 'Postive')], default='Postive', max_length=50),
        ),
    ]
