# Generated by Django 4.1.3 on 2022-11-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile_expense_alter_profile_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive')], max_length=50),
        ),
    ]
